package bd2.business;

public class ErrorCodes {

	public static final String EMAIL_ERRORCODE = "EMAIL_ERRORCODE";

	public static final String PASSWORD_MATCHING_ERRORCODE = "PASSWORD_MATCHING_ERRORCODE";

	public static final String PASSWORD_LENGTH_ERRORCODE = "PASSWORD_LENGTH_ERRORCODE";

	public static final String STRING_FIELD_FORMAT_ERRORCODE = "STRING_FIELD_FORMAT_ERRORCODE";

	public static final String FIELD_REQUIRED_ERRORCODE = "FIELD_REQUIRED_ERRORCODE";

	public static final String DATE_AFTER_TODAY_ERRORCODE = "DATE_AFTER_TODAY_ERRORCODE";

	public static final String WRONG_FORMAT_ERRORCODE = "WRONG_FORMAT_ERRORCODE";

	public static final String LOGIN_EXISTS_ERRORCODE = "LOGIN_EXISTS_ERRORCODE";

	public static final String EMAIL_EXISTS_ERRORCODE = "EMAIL_EXISTS_ERRORCODE";

	public static final String JUSTIFICATION_TOO_LONG_ERRORCODE = "JUSTIFICATION_TOO_LONG_ERRORCODE";

	public static final String COLLECTOR_NOT_CHOSEN = "COLLECTOR_NOT_CHOSEN";

	public static final String JUSTIFICATION_EMPTY = "JUSTIFICATION_EMPTY";
}
